timezone: UTC
permalink: pretty
lang:
    name: Castellano
    code: es
social:
    facebook: 'https://www.facebook.com/seedocare/'
    linkedin: 'https://www.linkedin.com/company/seedocare-com/'
langs:
    - { name: Castellano, code: es }
    - { name: English, code: en }
gems:
    - jekyll-sitemap
template: default
defaults:
    - { scope: { path: '', type: posts }, values: { type: post, layout: post } }
    - { scope: { path: '', type: pages }, values: { layout: page, lang: es } }
